### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by phoenixes94** [shaido987/KDD_wind_power_forecast#9]
hello！ here are some question. when I python train_xtgn.py ,It goes rong . the rong messages are following:

Traceback (most recent call last):
  File "train_xtgn.py", line 180, in <module>
    main(args, model_dir)
  File "train_xtgn.py", line 34, in main
    data_loader, _ = load_wp_dataset_mask(model_dir, args['ratio'], args['batch_size'], args['batch_size'],
  File "/csg/shzhou/bingcheng_KDD/KDD_wind_power_forecast-main/KDD_wind_power_forecast-main/methods/xtgn/data_process/util.py", line 154, in load_wp_dataset_mask
    cat_data = np.load(os.path.join(dataset_dir, category + f"_{ratio}_new_mask.npz"))
  File "/csg/shzhou/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'methods/checkpoints/xtgn-2/train_9_new_mask.npz'

wish you best!!!  hope receiving your answer！！！

**Comment by shaido987** [comment]
Hello,

You are correct. We preprocess the data and save it to a file in the model directory (train_9_new_mask.npz). The preprocessing also creates some other files and in the original code we only check if the adjacency matrix is present or not, if not we run the preprocessing steps.

However, we included the adjacency matrix in the repository to allow running the inference code directly without training. This made our check whether to preprocess the data or not fail (as the adjacency matrix is present but not the train_9_new_mask.npz file) which gives this error. I have added a fix in #10 so the method checks for both the adjacency matrix file and the train_9_new_mask.npz file. So it should work as intended now.

**Comment by phoenixes94** [comment]
ok, thank you very much!!!  
I think it is better that if  you consider to find a free time  making a video that describes the structure of your model and how to construct it. most learners will preciate it.

**Comment by shaido987** [comment]
There will be a technical report and a presentation video available sometime next week (most likely time). Although it will not contain anything specific on how to run the code it will explain the model structure and how everything works together.

**Comment by phoenixes94** [comment]
thank you very much!!! could you share your website when you post videos here or can I have your wechat ? My wechat is zs673249705. wish your best~

**Comment by shaido987** [comment]
I have added a link to the technical report with the model details and the presentation video in the readme file. :)
